version: 2
jobs:
  build:
    working_directory: ~/circlecibuild
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Production React Build
          command: npm run build
      - run: 
          name: Build Docker image 
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS $REGISTRY_NAME
      -run:
          name: Push Docker Image
          command: docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master