version: 2
jobs:
  build:
    working_directory: ~/circlecibuild
    environment:
      IMAGE_NAME: m0sscr.azurecr.io/iotdashboard
    docker:
      - image: nginx:1.15.2-alpine
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Node
          command: apk add --update nodejs npm
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-packages
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Production React Build
          command: npm run build
      - run: 
          name: Build Docker image 
          command: docker build -t $IMAGE_NAME:latest .
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master